// migrations/001_baseline.js
// ------------------------------------------------------------
// The schema as it was at commit e8b747d (Oct 2026), before versioned
// migrations existed. Every statement is "IF NOT EXISTS", so running it on
// a database that already has these tables changes nothing. That is what
// makes it safe as migration 001 on the live database.
// NEVER edit an applied migration: add a new numbered file instead.
// ------------------------------------------------------------
// Tables. "IF NOT EXISTS" means it is safe to run on every start.
// Dates are stored as text 'YYYY-MM-DD'. Money is stored in rupees (₹).
// "created_at" is text 'YYYY-MM-DD HH:MM:SS' in UTC (same as before).
// Yes/no columns stay as INTEGER 0/1 so API answers do not change.
// ------------------------------------------------------------
const NOW_TEXT = `(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))`;

const SCHEMA_SQL = `
  -- People who use the app
  CREATE TABLE IF NOT EXISTS users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at    TEXT NOT NULL DEFAULT ${NOW_TEXT}
  );

  -- Body + money details used for calculations (one row per user)
  CREATE TABLE IF NOT EXISTS profiles (
    user_id         INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    sex             TEXT,      -- 'male' or 'female'
    age             INTEGER,
    height_cm       DOUBLE PRECISION,
    weight_kg       DOUBLE PRECISION,
    activity_factor DOUBLE PRECISION DEFAULT 1.2, -- 1.2 sitting ... 1.9 very active
    goal            TEXT DEFAULT 'maintain', -- 'lose' | 'maintain' | 'gain'
    pace_kg_week    DOUBLE PRECISION DEFAULT 0.5,
    income          DOUBLE PRECISION DEFAULT 0,   -- monthly income in ₹
    neck_cm         DOUBLE PRECISION,  -- optional, for body fat %
    waist_cm        DOUBLE PRECISION,  -- optional, for body fat %
    hip_cm          DOUBLE PRECISION,  -- optional, women only, for body fat %
    step_goal       INTEGER DEFAULT 8000
  );

  -- Food library (seeded with Indian foods below)
  CREATE TABLE IF NOT EXISTS foods (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    serving    TEXT NOT NULL,   -- e.g. '1 katori (150 g)'
    kcal       DOUBLE PRECISION NOT NULL,
    protein_g  DOUBLE PRECISION NOT NULL,
    carbs_g    DOUBLE PRECISION NOT NULL,
    fat_g      DOUBLE PRECISION NOT NULL,
    verified   INTEGER NOT NULL DEFAULT 0, -- 1 = checked (seed list), 0 = added by a user
    created_by INTEGER                     -- who added a custom food (null for seeded foods)
  );

  -- What a user ate
  CREATE TABLE IF NOT EXISTS food_logs (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    food_id    INTEGER NOT NULL REFERENCES foods(id),
    date       TEXT NOT NULL,
    meal       TEXT NOT NULL,      -- breakfast | lunch | dinner | snack
    servings   DOUBLE PRECISION NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT ${NOW_TEXT}
  );

  -- Step count per day (sent by the phone app). One row per user per day.
  CREATE TABLE IF NOT EXISTS step_logs (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date    TEXT NOT NULL,
    steps   INTEGER NOT NULL,
    UNIQUE(user_id, date)
  );

  CREATE TABLE IF NOT EXISTS workouts (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date      TEXT NOT NULL,
    activity  TEXT NOT NULL,
    minutes   DOUBLE PRECISION NOT NULL,
    met       DOUBLE PRECISION NOT NULL,
    weight_kg DOUBLE PRECISION NOT NULL,
    kcal      DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS water_logs (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date    TEXT NOT NULL,
    ml      DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS sleep_logs (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date    TEXT NOT NULL,   -- the morning you woke up
    hours   DOUBLE PRECISION NOT NULL,
    quality INTEGER          -- 1 (bad) to 5 (great), optional
  );

  CREATE TABLE IF NOT EXISTS mood_logs (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date    TEXT NOT NULL,
    mood    INTEGER NOT NULL, -- 1 (sad) to 5 (happy)
    note    TEXT
  );

  CREATE TABLE IF NOT EXISTS weight_logs (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date      TEXT NOT NULL,
    weight_kg DOUBLE PRECISION NOT NULL
  );

  -- "Stand up and move" reminder settings (the phone app reads these)
  CREATE TABLE IF NOT EXISTS reminder_settings (
    user_id      INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    enabled      INTEGER NOT NULL DEFAULT 1, -- 1 = on, 0 = off
    interval_min INTEGER NOT NULL DEFAULT 60,
    start_hour   INTEGER NOT NULL DEFAULT 9,  -- only remind between these hours
    end_hour     INTEGER NOT NULL DEFAULT 21
  );

  -- ---------------- WEALTH ----------------
  CREATE TABLE IF NOT EXISTS expenses (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount   DOUBLE PRECISION NOT NULL,
    category TEXT NOT NULL,
    mode     TEXT NOT NULL,   -- UPI | Card | Cash
    note     TEXT,
    date     TEXT NOT NULL
  );

  -- Monthly budget per category, e.g. month '2026-10', 'Food', 6000
  CREATE TABLE IF NOT EXISTS budgets (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    month    TEXT NOT NULL,
    category TEXT NOT NULL,
    amount   DOUBLE PRECISION NOT NULL,
    UNIQUE(user_id, month, category)
  );

  CREATE TABLE IF NOT EXISTS savings_goals (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name     TEXT NOT NULL,
    target   DOUBLE PRECISION NOT NULL,
    saved    DOUBLE PRECISION NOT NULL DEFAULT 0,
    deadline TEXT            -- optional 'YYYY-MM-DD'
  );

  CREATE TABLE IF NOT EXISTS bills (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name      TEXT NOT NULL,
    amount    DOUBLE PRECISION NOT NULL,
    due_day   INTEGER NOT NULL, -- day of month 1-31
    recurring INTEGER NOT NULL DEFAULT 1
  );

  -- Which months a bill was paid in ('2026-10')
  CREATE TABLE IF NOT EXISTS bill_payments (
    bill_id INTEGER NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    month   TEXT NOT NULL,
    paid_at TEXT NOT NULL DEFAULT ${NOW_TEXT},
    PRIMARY KEY (bill_id, month)
  );

  -- ---------------- SUBSCRIPTIONS ----------------
  CREATE TABLE IF NOT EXISTS subscriptions (
    user_id    INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    plan       TEXT NOT NULL DEFAULT 'free',
    period     TEXT,           -- 'monthly' | 'quarterly' | 'yearly' | 'monthly_prepaid' | 'trial'
    status     TEXT NOT NULL DEFAULT 'active',
    expires_at TEXT,           -- ISO date-time, null for free
    trial_used INTEGER NOT NULL DEFAULT 0 -- 1 once the free trial is used
  );

  -- LEGACY (unused since Oct 2026): old payment-order table. Nothing reads or
  -- writes it any more; payments go through Google Play. Kept so existing
  -- databases are not changed (we never drop tables in init()).
  CREATE TABLE IF NOT EXISTS payments (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    order_id     TEXT NOT NULL UNIQUE,
    payment_id   TEXT,
    plan         TEXT NOT NULL,
    period       TEXT NOT NULL,
    amount_paise INTEGER NOT NULL,
    status       TEXT NOT NULL DEFAULT 'created', -- created | paid | failed
    created_at   TEXT NOT NULL DEFAULT ${NOW_TEXT}
  );

  -- Foods a user starred, so they show first and can be logged fast
  CREATE TABLE IF NOT EXISTS food_favourites (
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    food_id    INTEGER NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT ${NOW_TEXT},
    PRIMARY KEY (user_id, food_id)
  );

  -- Columns added after v1 (safe if they already exist)
  ALTER TABLE foods ADD COLUMN IF NOT EXISTS verified INTEGER NOT NULL DEFAULT 0;
  ALTER TABLE foods ADD COLUMN IF NOT EXISTS created_by INTEGER;
  ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS trial_used INTEGER NOT NULL DEFAULT 0;

  -- Google Play Billing (added Oct 2026). Where the current plan came from:
  -- NULL = trial / dev, 'google_play' = a Play subscription
  ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS source TEXT;
  ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS auto_renew INTEGER NOT NULL DEFAULT 0;
  ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS google_purchase_token TEXT;

  -- One row per Google Play purchase token (the latest state Google told us).
  -- purchase_token is the PRIMARY KEY, so one token can only belong to ONE user.
  -- user_id is NULL when Google told us about a token (RTDN) before the app did.
  CREATE TABLE IF NOT EXISTS google_play_purchases (
    purchase_token        TEXT PRIMARY KEY,
    user_id               INTEGER REFERENCES users(id) ON DELETE SET NULL,
    product_id            TEXT NOT NULL,          -- raphai_plus | raphai_pro | raphai_elite
    base_plan_id          TEXT,                   -- monthly | quarterly | yearly | monthly-prepaid
    offer_id              TEXT,                   -- e.g. the free-trial offer id
    plan                  TEXT NOT NULL,          -- plus | pro | elite
    period                TEXT,                   -- monthly | yearly
    subscription_state    TEXT NOT NULL,          -- SUBSCRIPTION_STATE_ACTIVE, ..._EXPIRED, ...
    expires_at            TIMESTAMPTZ,
    auto_renew            INTEGER NOT NULL DEFAULT 0,
    in_trial              INTEGER NOT NULL DEFAULT 0,
    acknowledged          INTEGER NOT NULL DEFAULT 0,
    linked_purchase_token TEXT,                   -- the older token this one replaced
    superseded_by         TEXT,                   -- set when a newer token replaced this one
    revoked_at            TIMESTAMPTZ,            -- set on a refund/revoke: this token never gives access again
    latest_order_id       TEXT,
    test_purchase         INTEGER NOT NULL DEFAULT 0,
    raw                   JSONB,                  -- Google's full answer (for debugging)
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  ALTER TABLE google_play_purchases ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;
  CREATE INDEX IF NOT EXISTS google_play_purchases_user ON google_play_purchases (user_id);

  -- ---------------- RAPHAI INTELLIGENCE (v2, Oct 2026) ----------------
  -- Sleep can be imported from Health Connect. source NULL = typed in by the user.
  ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS source TEXT;

  -- Daily activity from the phone (Health Connect or the pedometer). One row per user per day.
  CREATE TABLE IF NOT EXISTS activity_daily (
    user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date           TEXT NOT NULL,
    steps          INTEGER,
    distance_m     DOUBLE PRECISION,
    active_kcal    DOUBLE PRECISION,
    active_minutes INTEGER,
    resting_hr     INTEGER,
    source         TEXT,           -- health_connect | pedometer
    updated_at     TEXT NOT NULL DEFAULT ${NOW_TEXT},
    PRIMARY KEY (user_id, date)
  );

  -- RaphScore saved per day, so we can explain how it changed vs yesterday.
  -- overall is NULL when there was not enough data that day.
  CREATE TABLE IF NOT EXISTS raphscore_daily (
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date        TEXT NOT NULL,
    overall     INTEGER,
    areas       JSONB NOT NULL DEFAULT '{}'::jsonb,  -- { "health": 72, "fitness": null, ... }
    computed_at TEXT NOT NULL DEFAULT ${NOW_TEXT},
    PRIMARY KEY (user_id, date)
  );

  -- How often a user used a limited feature on a day (e.g. AI food parse: 5 a day on Free)
  CREATE TABLE IF NOT EXISTS feature_usage (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date    TEXT NOT NULL,
    feature TEXT NOT NULL,
    count   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, date, feature)
  );

  -- ---------------- PRIVACY (Oct 2026) ----------------
  -- Consent records: what the user agreed to, which version, yes/no, when.
  -- One row per change (latest row per type = current choice).
  -- No foreign key on purpose: the Privacy Policy keeps consent records for
  -- 1 year AFTER the account is deleted. account_deleted_at is set when the
  -- account goes, and the daily purge removes them a year later.
  CREATE TABLE IF NOT EXISTS consents (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            INTEGER NOT NULL,
    type               TEXT NOT NULL,   -- terms_privacy | health_connect | background_health | ads_personalised | gemini
    version            TEXT NOT NULL,
    granted            BOOLEAN NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    account_deleted_at TIMESTAMPTZ
  );
  CREATE INDEX IF NOT EXISTS consents_user ON consents (user_id, type, created_at);

  -- Security logs (kept 1 year, in this database = Mumbai, India).
  -- user_id has no foreign key so the log survives account deletion.
  CREATE TABLE IF NOT EXISTS security_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER,
    event      TEXT NOT NULL,   -- login_success | login_failed | password_change | account_deleted | export
    ip         TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  CREATE INDEX IF NOT EXISTS security_logs_created ON security_logs (created_at);

  -- Last time the user used the app (updated at most once a day by requireAuth).
  -- Recorded only: inactive accounts are NOT deleted automatically yet.
  ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ;

  -- Indexes that make the common "my rows for this date" lookups fast
  CREATE INDEX IF NOT EXISTS food_logs_user_date ON food_logs (user_id, date);
  CREATE INDEX IF NOT EXISTS workouts_user_date ON workouts (user_id, date);
  CREATE INDEX IF NOT EXISTS water_logs_user_date ON water_logs (user_id, date);
  CREATE INDEX IF NOT EXISTS sleep_logs_user_date ON sleep_logs (user_id, date);
  CREATE INDEX IF NOT EXISTS mood_logs_user_date ON mood_logs (user_id, date);
  CREATE INDEX IF NOT EXISTS weight_logs_user_date ON weight_logs (user_id, date);
  CREATE INDEX IF NOT EXISTS expenses_user_date ON expenses (user_id, date);
  CREATE INDEX IF NOT EXISTS step_logs_user_date ON step_logs (user_id, date);
`;


module.exports = { id: '001_baseline', sql: SCHEMA_SQL };
